# Generated by Django 3.2 on 2021-06-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
                ('university', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=20)),
                ('difficulty', models.IntegerField()),
                ('required_level', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clicked_count', models.IntegerField()),
            ],
        ),
    ]
