# Generated by Django 3.2 on 2021-06-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='comment',
            field=models.TextField(),
        ),
    ]
